# Generated by Django 5.0.3 on 2024-03-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_mesa_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='mesa',
        ),
        migrations.AddField(
            model_name='mesa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente'),
        ),
    ]
